/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CountryController;
import controllers.RegionController;
import daos.RegionDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import models.Country;
import javax.swing.table.DefaultTableModel;
import models.Region;
import tools.DBConnection;

/**
 *
 * @author gerydanu
 */
public class CountryView extends javax.swing.JInternalFrame {

    DBConnection connection = new DBConnection();
    CountryController cc = new CountryController(connection.getConnection());
    RegionController rc = new RegionController(connection.getConnection());
    
    /**
     * Creates new form Country
     */
    public CountryView() {
        initComponents();
        tampilTabelCountries();
        tampilRegion();
    }
    
    void tampilRegion() {
        for (Region region : rc.getAllData("", false)) {
            jComboRegionId.addItem(region.getId()+"-"+region.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAtas = new javax.swing.JPanel();
        jLabelCountries = new javax.swing.JLabel();
        jPanelKiri = new javax.swing.JPanel();
        jLabelCountryId = new javax.swing.JLabel();
        jLabelCountryName = new javax.swing.JLabel();
        jLabelRegionId = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSearchDelete = new javax.swing.JLabel();
        jPanelKanan = new javax.swing.JPanel();
        jTextCountryId = new javax.swing.JTextField();
        jTextCountryName = new javax.swing.JTextField();
        jComboRegionId = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();
        jTextSearch = new javax.swing.JTextField();
        jButtonDeleteId = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jCheckById = new javax.swing.JCheckBox();
        jPanelBawah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCountries = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        jLabelCountries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCountries.setText("COUNTRIES");
        jPanelAtas.add(jLabelCountries);

        getContentPane().add(jPanelAtas, java.awt.BorderLayout.PAGE_START);

        jPanelKiri.setLayout(new java.awt.GridLayout(9, 1, 5, 5));

        jLabelCountryId.setText("COUNTRY_ID");
        jPanelKiri.add(jLabelCountryId);

        jLabelCountryName.setText("COUNTRY_NAME");
        jPanelKiri.add(jLabelCountryName);

        jLabelRegionId.setText("REGION_ID");
        jPanelKiri.add(jLabelRegionId);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelKiri.add(jPanel1);

        jLabelSearchDelete.setText("Search / Delete");
        jPanelKiri.add(jLabelSearchDelete);

        getContentPane().add(jPanelKiri, java.awt.BorderLayout.LINE_START);

        jPanelKanan.setLayout(new java.awt.GridLayout(9, 1));

        jTextCountryId.setText("[ Country ID ]");
        jTextCountryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCountryIdActionPerformed(evt);
            }
        });
        jPanelKanan.add(jTextCountryId);

        jTextCountryName.setText("[ Country Name ]");
        jTextCountryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCountryNameActionPerformed(evt);
            }
        });
        jPanelKanan.add(jTextCountryName);

        jComboRegionId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        jComboRegionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRegionIdActionPerformed(evt);
            }
        });
        jPanelKanan.add(jComboRegionId);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanelKanan.add(jButtonSave);

        jTextSearch.setText("[ Search / Delete ]");
        jPanelKanan.add(jTextSearch);

        jButtonDeleteId.setText("Delete by ID");
        jButtonDeleteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteIdActionPerformed(evt);
            }
        });
        jPanelKanan.add(jButtonDeleteId);

        jButtonSearch.setText("Search");
        jPanelKanan.add(jButtonSearch);

        jCheckById.setText("Get by ID");
        jPanelKanan.add(jCheckById);

        getContentPane().add(jPanelKanan, java.awt.BorderLayout.CENTER);

        jTableCountries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Country_ID", "Country_Name", "Region_ID"
            }
        ));
        jScrollPane1.setViewportView(jTableCountries);

        javax.swing.GroupLayout jPanelBawahLayout = new javax.swing.GroupLayout(jPanelBawah);
        jPanelBawah.setLayout(jPanelBawahLayout);
        jPanelBawahLayout.setHorizontalGroup(
            jPanelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelBawahLayout.setVerticalGroup(
            jPanelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBawahLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBawah, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCountryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCountryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCountryIdActionPerformed

    private void jTextCountryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCountryNameActionPerformed

    }//GEN-LAST:event_jTextCountryNameActionPerformed

    private void jComboRegionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRegionIdActionPerformed
    }//GEN-LAST:event_jComboRegionIdActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        JOptionPane.showMessageDialog(rootPane, cc.insert(jTextCountryId.getText(), jTextCountryName.getText(), jComboRegionId.getActionCommand()));
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDeleteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteIdActionPerformed
        
    }//GEN-LAST:event_jButtonDeleteIdActionPerformed
    
    
    private void tampilTabelCountries() {
        DefaultTableModel tabelCountries = (DefaultTableModel) jTableCountries.getModel();
        tabelCountries.setRowCount(0);
        int hitung = 1;
        for (models.Country values : cc.getAllData()) {
            Object[] data = {hitung, values.getCountry_id(), values.getCountry_name(), values.getRegion_id()};
            tabelCountries.addRow(data);
            hitung++;
        }
//        for (CountryView values : cc.getAllData()) {
//            Object[] data = {hitung, values.getCountry_id(), values.getCountry_name(), values.getRegion_id()};
//            tabelCountries.addRow(data);
//            hitung++;
//        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteId;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBox jCheckById;
    private javax.swing.JComboBox<String> jComboRegionId;
    private javax.swing.JLabel jLabelCountries;
    private javax.swing.JLabel jLabelCountryId;
    private javax.swing.JLabel jLabelCountryName;
    private javax.swing.JLabel jLabelRegionId;
    private javax.swing.JLabel jLabelSearchDelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAtas;
    private javax.swing.JPanel jPanelBawah;
    private javax.swing.JPanel jPanelKanan;
    private javax.swing.JPanel jPanelKiri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCountries;
    private javax.swing.JTextField jTextCountryId;
    private javax.swing.JTextField jTextCountryName;
    private javax.swing.JTextField jTextSearch;
    // End of variables declaration//GEN-END:variables
}
