/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import controllers.JobController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import tools.DBConnection;

/**
 *
 * @author FES
 */
public class EmployeeView extends javax.swing.JInternalFrame {

    DBConnection connection = new DBConnection();
    EmployeeController ec = new EmployeeController(connection.getConnection());
    JobController jc = new JobController(connection.getConnection());
    
    DefaultTableModel tableModel;
    /**
     * Creates new form NewJInternalFrame
     */
    public EmployeeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEmployeeMain = new javax.swing.JPanel();
        jPEmployeeMainNorth = new javax.swing.JPanel();
        jLEmployeeTitle = new javax.swing.JLabel();
        jPEmployeeMainWest = new javax.swing.JPanel();
        jLEmployeeEmployeeId = new javax.swing.JLabel();
        jLEmployeeFirstName = new javax.swing.JLabel();
        jLEmployeeLastName = new javax.swing.JLabel();
        jLEmployeeEmail = new javax.swing.JLabel();
        jLEmployeePhoneNumber = new javax.swing.JLabel();
        jLEmployeeHireDate = new javax.swing.JLabel();
        jLEmployeeJobId = new javax.swing.JLabel();
        jLEmployeeSalary = new javax.swing.JLabel();
        jLEmployeeCommissionPct = new javax.swing.JLabel();
        jLEmployeeManagerId = new javax.swing.JLabel();
        jLEmployeeDepartmentId = new javax.swing.JLabel();
        jSEmployees1 = new javax.swing.JSeparator();
        jLEmployeeSearch = new javax.swing.JLabel();
        jPEmployeeMainCenter = new javax.swing.JPanel();
        jTFEmployeeEmployeeId = new javax.swing.JTextField();
        jTFEmployeeFirstName = new javax.swing.JTextField();
        jTFEmployeeLastName = new javax.swing.JTextField();
        jTFEmployeeEmail = new javax.swing.JTextField();
        jTFEmployeePhoneNumber = new javax.swing.JTextField();
        jTFEmployeeHireDate = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTFEmployeeSalary = new javax.swing.JTextField();
        jTFEmployeeCommissionPct = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPEmployeeMainCenterContent1 = new javax.swing.JPanel();
        jBEmployeeInsert = new javax.swing.JButton();
        jBEmployeeUpdate = new javax.swing.JButton();
        jPEmployeeMainCenterContent2 = new javax.swing.JPanel();
        jTFEmployeeSearch = new javax.swing.JTextField();
        jPEmployeeMainCenterContent3 = new javax.swing.JPanel();
        jBEmployeeDelete = new javax.swing.JButton();
        jSEmployees2 = new javax.swing.JSeparator();
        jBEmployeeSearch = new javax.swing.JButton();
        jCBEmployeeisGetById = new javax.swing.JCheckBox();
        jSEmployees3 = new javax.swing.JSeparator();
        jBEmployeeGetAll = new javax.swing.JButton();
        jPEmployeeMainSouth = new javax.swing.JPanel();
        jSPEmployee = new javax.swing.JScrollPane();
        jTEmployee = new javax.swing.JTable();

        setClosable(true);
        setVisible(true);

        jPEmployeeMain.setLayout(new java.awt.BorderLayout(1, 1));

        jLEmployeeTitle.setText("EMPLOYEES");
        jPEmployeeMainNorth.add(jLEmployeeTitle);

        jPEmployeeMain.add(jPEmployeeMainNorth, java.awt.BorderLayout.PAGE_START);

        jPEmployeeMainWest.setLayout(new java.awt.GridLayout(14, 1));

        jLEmployeeEmployeeId.setText("Employee ID");
        jPEmployeeMainWest.add(jLEmployeeEmployeeId);

        jLEmployeeFirstName.setText("First Name");
        jPEmployeeMainWest.add(jLEmployeeFirstName);

        jLEmployeeLastName.setText("Last Name");
        jPEmployeeMainWest.add(jLEmployeeLastName);

        jLEmployeeEmail.setText("Email");
        jPEmployeeMainWest.add(jLEmployeeEmail);

        jLEmployeePhoneNumber.setText("Phone Number");
        jPEmployeeMainWest.add(jLEmployeePhoneNumber);

        jLEmployeeHireDate.setText("Hire Date");
        jPEmployeeMainWest.add(jLEmployeeHireDate);

        jLEmployeeJobId.setText("Job Id");
        jPEmployeeMainWest.add(jLEmployeeJobId);

        jLEmployeeSalary.setText("Salary");
        jPEmployeeMainWest.add(jLEmployeeSalary);

        jLEmployeeCommissionPct.setText("Commission Pct");
        jPEmployeeMainWest.add(jLEmployeeCommissionPct);

        jLEmployeeManagerId.setText("Manager Id");
        jPEmployeeMainWest.add(jLEmployeeManagerId);

        jLEmployeeDepartmentId.setText("Department Id");
        jPEmployeeMainWest.add(jLEmployeeDepartmentId);
        jPEmployeeMainWest.add(jSEmployees1);

        jLEmployeeSearch.setText("Search/Delete");
        jPEmployeeMainWest.add(jLEmployeeSearch);

        jPEmployeeMain.add(jPEmployeeMainWest, java.awt.BorderLayout.LINE_START);

        jPEmployeeMainCenter.setLayout(new java.awt.GridLayout(14, 1));

        jTFEmployeeEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmployeeEmployeeIdActionPerformed(evt);
            }
        });
        jPEmployeeMainCenter.add(jTFEmployeeEmployeeId);
        jPEmployeeMainCenter.add(jTFEmployeeFirstName);
        jPEmployeeMainCenter.add(jTFEmployeeLastName);
        jPEmployeeMainCenter.add(jTFEmployeeEmail);
        jPEmployeeMainCenter.add(jTFEmployeePhoneNumber);
        jPEmployeeMainCenter.add(jTFEmployeeHireDate);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPEmployeeMainCenter.add(jComboBox3);
        jPEmployeeMainCenter.add(jTFEmployeeSalary);
        jPEmployeeMainCenter.add(jTFEmployeeCommissionPct);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPEmployeeMainCenter.add(jComboBox2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPEmployeeMainCenter.add(jComboBox1);

        jPEmployeeMainCenterContent1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBEmployeeInsert.setText("Insert");
        jBEmployeeInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmployeeInsertActionPerformed(evt);
            }
        });
        jPEmployeeMainCenterContent1.add(jBEmployeeInsert);

        jBEmployeeUpdate.setText("Update");
        jBEmployeeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmployeeUpdateActionPerformed(evt);
            }
        });
        jPEmployeeMainCenterContent1.add(jBEmployeeUpdate);

        jPEmployeeMainCenter.add(jPEmployeeMainCenterContent1);

        jPEmployeeMainCenterContent2.setLayout(new java.awt.GridLayout());
        jPEmployeeMainCenterContent2.add(jTFEmployeeSearch);

        jPEmployeeMainCenter.add(jPEmployeeMainCenterContent2);

        jPEmployeeMainCenterContent3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBEmployeeDelete.setText("Delete by ID");
        jBEmployeeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmployeeDeleteActionPerformed(evt);
            }
        });
        jPEmployeeMainCenterContent3.add(jBEmployeeDelete);
        jPEmployeeMainCenterContent3.add(jSEmployees2);

        jBEmployeeSearch.setText("Search");
        jBEmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmployeeSearchActionPerformed(evt);
            }
        });
        jPEmployeeMainCenterContent3.add(jBEmployeeSearch);

        jCBEmployeeisGetById.setText("Get By ID");
        jCBEmployeeisGetById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEmployeeisGetByIdActionPerformed(evt);
            }
        });
        jPEmployeeMainCenterContent3.add(jCBEmployeeisGetById);
        jPEmployeeMainCenterContent3.add(jSEmployees3);

        jBEmployeeGetAll.setText("Get All Data");
        jBEmployeeGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmployeeGetAllActionPerformed(evt);
            }
        });
        jPEmployeeMainCenterContent3.add(jBEmployeeGetAll);

        jPEmployeeMainCenter.add(jPEmployeeMainCenterContent3);

        jPEmployeeMain.add(jPEmployeeMainCenter, java.awt.BorderLayout.CENTER);

        jSPEmployee.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jSPEmployee.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Employee ID", "First Name", "Last Name", "Email", "Phone Number", "Hire Date", "Job ID", "Salary", "Commission Pct", "Manager ID", "Department ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jSPEmployee.setViewportView(jTEmployee);

        javax.swing.GroupLayout jPEmployeeMainSouthLayout = new javax.swing.GroupLayout(jPEmployeeMainSouth);
        jPEmployeeMainSouth.setLayout(jPEmployeeMainSouthLayout);
        jPEmployeeMainSouthLayout.setHorizontalGroup(
            jPEmployeeMainSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        jPEmployeeMainSouthLayout.setVerticalGroup(
            jPEmployeeMainSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPEmployeeMain.add(jPEmployeeMainSouth, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEmployeeMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEmployeeMain, javax.swing.GroupLayout.PREFERRED_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFEmployeeEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmployeeEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmployeeEmployeeIdActionPerformed

    private void jBEmployeeInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmployeeInsertActionPerformed
        ec.insert(jTFEmployeeEmployeeId.getText(), jTFEmployeeFirstName.getText(), jTFEmployeeLastName.getText(), jTFEmployeeEmail.getText(), jTFEmployeePhoneNumber.getText(), jTFEmployeeHireDate.getText(), jTFEmployeeJobId.getText(), jTFEmployeeSalary.getText(), jTFEmployeeCommissionPct.getText(), jTFEmployeeManagerId.getText(), jTFEmployeeDepartmentId.getText());
    }//GEN-LAST:event_jBEmployeeInsertActionPerformed

    private void jBEmployeeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmployeeUpdateActionPerformed
        ec.update(jTFEmployeeEmployeeId.getText(), jTFEmployeeFirstName.getText(), jTFEmployeeLastName.getText(), jTFEmployeeEmail.getText(), jTFEmployeePhoneNumber.getText(), jTFEmployeeHireDate.getText(), jTFEmployeeJobId.getText(), jTFEmployeeSalary.getText(), jTFEmployeeCommissionPct.getText(), jTFEmployeeManagerId.getText(), jTFEmployeeDepartmentId.getText());
    }//GEN-LAST:event_jBEmployeeUpdateActionPerformed

    private void jBEmployeeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmployeeDeleteActionPerformed
        ec.delete(jTFEmployeeSearch.getText());
    }//GEN-LAST:event_jBEmployeeDeleteActionPerformed

    private void jBEmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmployeeSearchActionPerformed
        DefaultTableModel tableModelEmployee = (DefaultTableModel) jTEmployee.getModel();
        tableModelEmployee.setRowCount(0);
        for (EmployeeView value : ec.searchData(jTFEmployeeSearch.getText().toString(), jCBEmployeeisGetById.isSelected())) {
            Object[] data = {value.getEmployeeId(),value.getFirst_name(),
                value.getLast_name(),value.getEmail(),value.getPhone_number(),
                value.getHire_date(),value.getJob_id(),value.getSalary(),
                value.getCommission_pct(),value.getManager_id(),value.getDepartment_id()
            };
            tableModelEmployee.addRow(data);
        }

    }//GEN-LAST:event_jBEmployeeSearchActionPerformed

    private void jCBEmployeeisGetByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEmployeeisGetByIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEmployeeisGetByIdActionPerformed

    private void jBEmployeeGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmployeeGetAllActionPerformed
        DefaultTableModel tableModelEmployee = (DefaultTableModel) jTEmployee.getModel();
        tableModelEmployee.setRowCount(0);
        for (EmployeeView value : ec.getAllData()) {
            Object[] data = {value.getEmployeeId(),value.getFirst_name(),
                value.getLast_name(),value.getEmail(),value.getPhone_number(),
                value.getHire_date(),value.getJob_id(),value.getSalary(),
                value.getCommission_pct(),value.getManager_id(),value.getDepartment_id()
            };
            tableModelEmployee.addRow(data);
        }

    }//GEN-LAST:event_jBEmployeeGetAllActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        
        for (Object object : col) {
            
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private ArrayList<String> getJobId(){
        ArrayList<String> list = new ArrayList<>();
        for (models.Job value : jc.getAll()) {
            list.add(value.getId());
        }
        return list;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEmployeeDelete;
    private javax.swing.JButton jBEmployeeGetAll;
    private javax.swing.JButton jBEmployeeInsert;
    private javax.swing.JButton jBEmployeeSearch;
    private javax.swing.JButton jBEmployeeUpdate;
    private javax.swing.JCheckBox jCBEmployeeisGetById;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLEmployeeCommissionPct;
    private javax.swing.JLabel jLEmployeeDepartmentId;
    private javax.swing.JLabel jLEmployeeEmail;
    private javax.swing.JLabel jLEmployeeEmployeeId;
    private javax.swing.JLabel jLEmployeeFirstName;
    private javax.swing.JLabel jLEmployeeHireDate;
    private javax.swing.JLabel jLEmployeeJobId;
    private javax.swing.JLabel jLEmployeeLastName;
    private javax.swing.JLabel jLEmployeeManagerId;
    private javax.swing.JLabel jLEmployeePhoneNumber;
    private javax.swing.JLabel jLEmployeeSalary;
    private javax.swing.JLabel jLEmployeeSearch;
    private javax.swing.JLabel jLEmployeeTitle;
    private javax.swing.JPanel jPEmployeeMain;
    private javax.swing.JPanel jPEmployeeMainCenter;
    private javax.swing.JPanel jPEmployeeMainCenterContent1;
    private javax.swing.JPanel jPEmployeeMainCenterContent2;
    private javax.swing.JPanel jPEmployeeMainCenterContent3;
    private javax.swing.JPanel jPEmployeeMainNorth;
    private javax.swing.JPanel jPEmployeeMainSouth;
    private javax.swing.JPanel jPEmployeeMainWest;
    private javax.swing.JSeparator jSEmployees1;
    private javax.swing.JSeparator jSEmployees2;
    private javax.swing.JSeparator jSEmployees3;
    private javax.swing.JScrollPane jSPEmployee;
    private javax.swing.JTable jTEmployee;
    private javax.swing.JTextField jTFEmployeeCommissionPct;
    private javax.swing.JTextField jTFEmployeeEmail;
    private javax.swing.JTextField jTFEmployeeEmployeeId;
    private javax.swing.JTextField jTFEmployeeFirstName;
    private javax.swing.JTextField jTFEmployeeHireDate;
    private javax.swing.JTextField jTFEmployeeLastName;
    private javax.swing.JTextField jTFEmployeePhoneNumber;
    private javax.swing.JTextField jTFEmployeeSalary;
    private javax.swing.JTextField jTFEmployeeSearch;
    // End of variables declaration//GEN-END:variables
}
